# Generated by Django 4.1.4 on 2023-07-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tg',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status_en',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10, null=True, verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status_ru',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10, null=True, verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status_tg',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10, null=True, verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_en',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_ru',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_tg',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
