# Generated by Django 4.1.4 on 2023-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_color_name_en_color_name_ru_color_name_tg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='title',
            field=models.CharField(default='ProductVariant', max_length=70),
        ),
    ]
