# Generated by Django 4.1.4 on 2023-07-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_productvariant_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='title_en',
            field=models.CharField(default='ProductVariant', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='title_ru',
            field=models.CharField(default='ProductVariant', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='title_tg',
            field=models.CharField(default='ProductVariant', max_length=70, null=True),
        ),
    ]
