# Generated by Django 4.1.4 on 2023-08-08 04:29

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_productvariant_title_en_productvariant_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='thumb.jpg', upload_to=Product.models.Product.upload_thumb, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=Product.models.Product.upload_file_name, verbose_name='image'),
        ),
    ]
