# Generated by Django 4.1.4 on 2023-08-08 04:40

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_product_thumbnail_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumb.jpg', null=True, upload_to=Product.models.Product.upload_thumb, verbose_name='thumbnail'),
        ),
    ]
