# Generated by Django 4.1.4 on 2023-08-09 14:04

import Product.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='pvid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=20, prefix='pvid', unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumb.jpg', null=True, upload_to=Product.models.ProductVariant.upload_thumb, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=Product.models.ProductVariant.upload_file_name, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.productvariant')),
            ],
            options={
                'verbose_name': 'Product Variant Image',
                'verbose_name_plural': 'Product Variant Images',
            },
        ),
        migrations.CreateModel(
            name='ProductCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.PositiveIntegerField(default=0, help_text='Available stock for this variant', verbose_name='Inventory')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.color', verbose_name='Color')),
                ('product_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productvariant', verbose_name='ProductVariant')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.size', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Product Combination',
                'verbose_name_plural': 'Product Combinations',
            },
        ),
    ]
