# Generated by Django 4.1.4 on 2023-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_productvariant_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_status_en',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10, null=True, verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_status_ru',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10, null=True, verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_status_tg',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10, null=True, verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='specification_en',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='specification_ru',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='specification_tg',
            field=models.TextField(blank=True, null=True, verbose_name='specification'),
        ),
    ]
