# Generated by Django 4.1.4 on 2023-08-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_productcombination_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Old Price'),
        ),
    ]
