# Generated by Django <version> on YYYY-MM-DD HH:MM

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # any dependencies on other migrations
    ]

    operations = [
        # list of operations
    ]
