# Generated by Django 4.1.4 on 2023-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_tg', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('image', models.ImageField(default='carousel.jpg', upload_to='carousel_images/', verbose_name='image')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('caption_en', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('caption_ru', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('caption_tg', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10, verbose_name='Status')),
                ('status_en', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10, null=True, verbose_name='Status')),
                ('status_ru', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10, null=True, verbose_name='Status')),
                ('status_tg', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10, null=True, verbose_name='Status')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Carousel Item',
                'verbose_name_plural': 'Carousel Items',
            },
        ),
    ]
